products = [
  [
    {
      id: 1,
      name: "Aveeno Baby Calming Comfort Bath & Lotion Set",
      img: "./asset/image/product/1/1.jpg",
      price: "15.00",
      description: [
        "2-piece Aveeno Baby Calming Comfort Bath & Lotion Set provides gentle and calming skin care specially designed for baby's dry, sensitive, delicate skin",
        "This baby bath set uses gentle bath time formulas with relaxing lavender and vanilla scents which are known to help soothe and calm baby before bed",
        "Aveeno Baby Calming Comfort Bath and Body Wash is a rich lathering cleanser that is tear-free and soap-free and, when combined with a warm bath, is clinically shown to soothe and comfort your fussy baby before bedtime",
        "Clinical studies show that massage calms babies, improving their overall well-being so after a bath, the Calming Comfort Moisturizing Lotion can help babies relax before bedtime and features a non-greasy, moisture-rich natural oatmeal formula",
        "Baby bath products are pH-balanced and paraben- phenoxyethanol- and phthalate-free, so they're gentle enough for baby's sensitive skin and leave it feeling soft, smooth, and healthy. Aveeno is a pediatrician and dermatologist recommended brand",
      ],
      imgs: ["1", "2", "3", "4"],
    },
    {
      id: 2,
      name: "Baby Merlin's Magic Sleepsuit",
      img: "./asset/image/product/1/2.jpg",
      price: "25.20",
      description: [
        "Outer layer 100% cotton, Inner layer 100% cotton, Fill 100% polyester",
        "The Merlin Magic Sleepsuit is the original swaddle transition product",
        "The Magic Sleepsuit is designed for back sleeping in the crib at the recommended room temperature for babies",
        "Baby Merlin's Magic Sleepsuit was invented by a mother of four and pediatric physical therapist",
        "The Magic Sleepsuit helps establish good sleep habits, and provides parents peace of mind that their baby is getting adequate rest for proper growth and development",
        "Proper fit and timing of introduction are critical to the safety and effectiveness of Baby Merlin's Magic Sleepsuit",
      ],
      imgs: ["1", "2", "3", "4"],
    },
    {
      id: 3,
      name: "Baby Hair Brush and Comb Set",
      img: "./asset/image/product/1/3.jpg",
      price: "243.25",
      description: [
        "Soft Natural Goat Hair Bristles Beech Wood Handle",
        "Soft Natural Goat Hair Bristles Beech Wood Handle",
        "All Natural - We use natural soft goat bristles, bamboo, beech wood and pear wood for all our hairbrushes and combs. Handmade with love and perfectly safe for newborns, toddlers and older kids.",
        "Prevents Cradle Cap - We use soft natural premium grade goat bristles which help in evenly distributing the natural oils in your baby’s hair for a healthier and cleaner scalp. Daily scalp massages can help prevent or reduce cradle cap from building up and also protects your baby's soft spot.",
        "Suitable For Wet & Dry Hair - Use on wet and dry hair. Comes with a 100% cotton string attached to the hair brushes for easy hanging.",
        "Relaxation - Brushing your baby's scalp daily can help with blood circulation and relaxation for your baby before a good night's sleep. Keeps your baby happy and healthy!",
        "Perfect Baby Shower Gift For Boys & Girls - Parents love cute and thoughtful gifts Our hairbrush and comb set comes in a 3-in-1 full hair grooming set, which grows with the baby. Beautiful gift box included.",
      ],
      imgs: ["1", "2", "3", "4", "5"],
    },
    {
      id: 4,
      name: "Gift Set, 5 Trial Size Baby Skin Care Products, Lotion, & Shampoo",
      img: "./asset/image/product/1/4.jpg",
      price: "13.65",
      description: [
        "BABY BATH PRODUCTS: Shampoo & Wash and Buttermilk Soap gently cleanse and soften baby's delicate, sensitive skin for irresistible silky smoothness",
        "BABY SKIN CARE: Daily Cream-to-Powder diaper rash cream, Original Nourishing Lotion, and Nourishing Oil moisturize and protect baby's skin from irritations",
        "ALL NATURAL: Give baby the freshest start with these natural baby care products formulated without phthalates parabens or petrolatum",
        "PEDIATRICIAN TESTED: These baby essentials are clinically proven to be safe, effective and non-irritating to nurture newborn skin",
        "BURTS BEES GIFT SET: This baby gift set contains travel size cleansing and moisturizing baby skin care products that make the perfect gift for mom and newborn alike",
      ],
      imgs: ["1", "2", "3"],
    },
    {
      id: 5,
      name: "Folding Travel Potty Seat for Babies",
      img: "./asset/image/product/1/5.jpg",
      price: "33.89",
      description: [
        "Our Folding Travel Toilet Seat fits most standard and public toilets securely. The stylish pink color is perfect for toddler girls.",
        "Award winning: Received the Drug Store News/ECRM 1st Place 2019 Buyer’s Choice Award!",
        "Perfect for on the Go: Small, lightweight, and includes a free travel bag that makes it easy to take around.",
        "8 super-suction cups keep it very sturdy, allowing toddlers to gain confidence when using the bathroom as a beginner.",
        "BPA Free materials. The manufacturer includes a 10 year warranty.",
      ],
      imgs: ["1", "2", "3", "4"],
    },
    {
      id: 6,
      name: "Johnson's First Touch Baby Gift Set",
      img: "./asset/image/product/1/6.jpg",
      price: "63.40",
      description: [
        "Johnson's First Touch Baby Gift Set, contains a selection of gentle products to cleanse, moisturize, and care for your baby's delicate skin and hair",
        "This baby gift set for new parents contains an assortment of four baby skin care products - baby wash, baby shampoo, baby lotion, diaper rash cream, plus one reusable bath caddy with handle",
        "The products in this gift set feature a formula that is 100% gentle and free of dyes, parabens and phthalates",
        "This gift pack is formulated to be gentle, never harsh; is good for all ages, and is pediatrician-tested. It makes the perfect gift for soon-to-be parents for any in-person or virtual baby shower",
        "We collaborated with and listened to 11,500 parents, midwives, and pediatricians around the world to design products are that are specially designed for baby's delicate skin",
      ],
      imgs: ["1", "2", "3", "4"],
    },
  ],
  [
    {
      id: 1,
      name: "Mama Bear Organic Baby Food",
      img: "./asset/image/product/2/1.jpg",
      price: "17.48",
      description: [
        "Twelve 4-ounce pouches of stage 2 baby food, for babies 6+ months",
        "USDA Organic, non-GMO ingredients, gluten free",
        "No artificial colors or flavors",
        "Kosher: Orthodox Union",
        "Made in the U.S.A. from U.S. and imported ingredients",
        "Satisfaction Guarantee: We’re proud of our products. If you aren’t satisfied, we’ll refund you for any reason within a year of purchase. 1-877-485-0385",
      ],
      imgs: ["1", "2", "3", "4"],
    },
    {
      id: 2,
      name: "Baby Bellies Lentil Wheels",
      img: "./asset/image/product/2/2.jpg",
      price: "11.80",
      description: [
        "Organic Multigrain Baby Snacks: These crunchy organic lentil and corn snacks are baked, not fried, and sprinkled with beetroot and strawberry for a handy on-the-go snack; Ideal for second stage snacking",
        "Age-appropriate: These snacks are specially designed to support natural child progression, helping encourage palate and motor skill development so parents can naturally nurture happy little people",
        "Food Discovery: Our Baby Bellies range is for babies from 7+ months (Tasty Textures) and 10+ months (More to Explore).They're perfect for the early stages of a life-long food discovery journey",
        "Exploring First Foods: Our Baby Snacks introduce subtle new flavors and textures, with soft shapes that are perfect for your baby to hold in their tiny hands and begin developing their motor skills",
      ],
      imgs: ["1", "2", "3", "4"],
    },
    {
      id: 3,
      name: "NatureBond Baby Food Feeder/Fruit Feeder Pacifier",
      img: "./asset/image/product/2/3.jpg",
      price: "13.99",
      description: [
        "★ MOST VALUE FOR MONEY BABY FRUIT / FOOD FEEDERS & TEETHERS (2 PCS w 6 Silicone Teats) – NatureBond Baby Fruit Feeders and Teethers are designed in candy-like colors that stimulate baby’s appetite for consumption of natural nutrients from fruits and vegetables. It is also a safe way to introduce our little ones to solid food while they go through weaning and teething phase. The All-IN-1 feeder can also soothe baby's teething discomfort by massaging the gums through chewing.",
        "★ QUALITY & SAFETY ASSURANCE – It is the only baby food / fruit feeder certified by World’s Leader in Testing, Inspection and Certification (TIC),Bureau Veritas USA, to be BPA Free, Latex Free, Lead Free and Phthalates Free.",
        "★ DESIGNED TO BE EASY TO DISMANTLE AND WASH/CLEAN – Our designers ensure the feeder is easy to dismantle and wash as hygiene and safety are our topmost priority. Unlike other feeders, NatureBond feeder has no irremovable components and can be fully dismantled for washing and cleaning purposes.",
      ],
      imgs: ["1", "2", "3"],
    },
    {
      id: 4,
      name: "Happy Baby Organic Yogis Freeze-Dried Yogurt & Fruit Snacks",
      img: "./asset/image/product/2/4.jpg",
      price: "59.29",
      description: [
        "Sweet Yogi: Little drops of goodness Made with wholesome yogurt and organic fruit, Happy Baby Yogis are melt-in-your-mouth, freeze-dried yogurt drops that provide babies and toddlers with a delicious baby or toddler snack that you can feel good about!",
        "Organic Snacks For Baby: Happy Baby goes beyond baby food with delicious, Superfood Puffs and freeze-dried yogurt snacks Babies may be ready for our delicious snacks when they can crawl on their hands and knees, without their tummy touching the ground",
        "Happy Baby: At Happy Baby Organics, we provide organic and delicious options for your baby's nutritional journey We develop premium organic recipes perfectly matched with your child's age and stage This is enlightened nutrition for every family",
        "Mindfully Made: We develop premium organic recipes perfectly matched with your child's age and stage Explore our snacks & meals for growing babies, toddlers & kids, from baby food pouches to freeze-dried yogurt treats, organic Cereals & Toddler Snacks",
      ],
      imgs: ["1", "2", "3", "4"],
    },
    {
      id: 5,
      name: "Plum Organics Mighty 4",
      img: "./asset/image/product/2/5.jpg",
      price: "26.88",
      description: [
        "GREAT BLENDS OF FRUITS, VEGGIES, PROTEIN & GRAINS: Banana, Blueberry, Sweet Potato, Carrot, Greek Yogurt & Millet; Strawberry, Banana, Greek Yogurt, Kale, Amaranth & Oat; Banana, Kiwi, Spinach, Greek Yogurt & Barley are fun, yummy, and real - a favorite to fuel your active tot",
        "RESEALABLE POUCHES ARE EASY TO USE: Non-BPA, child-safe, and with a recyclable cap, our pouches can serve as much yummy, nutritious food as baby needs at home or on-the-go",
        "WE'RE A B CORP: At Plum Organics, we're committed to our customers and our planet, and are focused on sustainable product design and safe ingredient sourcing",
        "VARIETY PACK OF 18 POUCHES: Ships as a pack of 18 4-ounce pouches (includes 6 pouches each of Banana, Blueberry, Sweet Potato, Carrot, Greek Yogurt & Millet; Strawberry, Banana, Greek Yogurt, Kale, Amaranth & Oat; Banana, Kiwi, Spinach, Greek Yogurt & Barley)",
      ],
      imgs: ["1", "2", "3", "4"],
    },
  ],
  [
    {
      id: 1,
      name: "Baby Einstein Take Along Tunes Musical Toy",
      img: "./asset/image/product/3/1.jpg",
      price: "9.19",
      description: [
        "A best selling favorite with thousands of 5 star ratings",
        "Inspires a lifelong love of music",
        "Baby can switch between 10 total melodies",
        "Perfectly sized for ages 3 to 36 months",
        "Volume control is music to mom & dad’s ears",
        "Easy to wipe down and clean",
      ],
      imgs: ["1", "2", "3"],
    },
    {
      id: 2,
      name: "MAGIFIRE Tummy Time Baby Water Mat",
      img: "./asset/image/product/3/2.jpg",
      price: "13.68",
      description: [
        "SUPREME QUALITY & 100% LEAK PROOF: Our baby water mat are made of durable 100% BPA-free & food grade PVC materials. Each of our water play mat has been strictly tested for NO LEAK and durability. No need to worry about messy accident",
        "BEST TUMMY TIME TOY: Enjoy the water time without getting wet! Your infant baby would be fascinated by the bright sea world and cute floating toys in the water. Parents can also have a fun time for watching the baby laugh and play. It is also a good sensory toy after baby know how to crawl and walk.",
        "PROMOTE BABY DEVELOPMENT: Tummy time water play mat helps strengthen baby’s leg and arm muscles for early development. Aside from preventing a flat head, this sensory baby mat can also delight brain development and enhancing hand-eye coordination",
        "EASY TO USE & PACK: Set the baby water mat by simply inflate the outer ring and fill the interior part with water! After use it, you can just empty the mat, fold it, and pack it into your purse or suitcase! It would also be a great gift for baby shower",
      ],
      imgs: ["1", "2", "3"],
    },
    {
      id: 3,
      name: "Sassy Stacks of Circles Stacking Ring",
      img: "./asset/image/product/3/3.jpg",
      price: "8.99",
      description: [
        "Straight post accepts different sized rings, strengthening hand-eye coordination",
        "Chunky rings make it easy for baby to grasp, strengthening fine motor skills",
        "Each ring features a different texture and weight; Textural variety is great for mouthing!",
        "Colorful beads in the clear ring allowing baby to connect the sound to sight",
      ],
      imgs: ["1", "2", "3"],
    },
    {
      id: 4,
      name: "iPlay, iLearn 10pcs Baby Rattle Toys",
      img: "./asset/image/product/3/4.jpg",
      price: "25.72",
      description: [
        "5Pcs colored Rattles/Teethers for different stages of your baby's development. Age-Specific design for your lovely baby.",
        "Great size for baby's small hands. They're easy to hold.",
        "Each rattle corresponds to a dinosaur shape. Bright colors stimulate the baby's vision.",
        "The soft silicone teether can help your baby relieve teething discomfort.",
        "Great gift for baby showers, suitable for nursery child care - easy to clean and store hygienically in their own container. Great stroller toy.",
      ],
      imgs: ["1", "2", "3", "4"],
    },
    {
      id: 5,
      name: "teytoy My First Soft Book",
      img: "./asset/image/product/3/5.jpg",
      price: "16.99",
      description: [
        "★MY FIRST SOFT BOOK - Baby first book teaches your little one how different things feel by touch with these soft books, and teaches them basic reading and comprehension,These cloth activity book also stimulate baby first year memory.",
        "★MULTIPLE THEMES IN ONE PACKAGE - No need to search for various books,Our early development toys (12 packs) are ready for your baby:sea world,animal world,number,vegetable,fruit,vehice shapes,nature ,visual training,expression,colors,wearing.",
        "★ALL FOR BABY'S SAFE - Our cloth book is totally safe for your baby,Made of high quality of fabric,which is light, non-toxic, durable, tear-resistant and washable.Because babies put everything into their mouth, the quality of this book is extremely important.",
        "★PERFECT BABY SHOWER GIFT - Sharing these soft books offers both parents and baby a perfect opportunity to bond in a warm and loving way. You can read these books with your little one, lead it to discover new things and explore this new world, teach it how to recognize and speak the words.It is a perfect gift, a delight kid activity book or baby book set.",
      ],
      imgs: ["1", "2", "3", "4"],
    },
    {
      id: 6,
      name: "VTech Wiggle and Crawl Ball,Multicolor",
      img: "./asset/image/product/3/6.jpg",
      price: "13.59",
      description: [
        "Move and crawl with the animal friends on the Wiggle and Crawl Ball by VTech",
        "Interactive ball wiggles and wobbles on its own encouraging your little one to chase after it; features 45+ playful songs, melodies, sounds and cheerful phrases",
        "Press the dog, cat and bear buttons to hone fine motor skills and learn about animals, colors and numbers; 6 interactive animals encourage play",
        "Five flashing lights attract your baby's attention while spinning and twisting animals encourage interaction; play and crawl with the moving ball",
        "Requires 3 AA batteries (batteries included for demo purposes only; new batteries recommended for regular use); intended for ages 6 months to 3 years",
      ],
      imgs: ["1", "2", "3"],
    },
  ],
];
